language: generic

matrix:
  include:
    - script:
        - bin/fetch-configlet
        - bin/configlet lint .
        - docker run -v `pwd`:/swift swift:4.0.2 bash -c "cd /swift && ./xswift-test-spm"
      env: JOB=Linux40
      sudo: required
      services: docker
    - script:
        - bin/fetch-configlet
        - bin/configlet lint .
        - docker run -v `pwd`:/swift norionomura/sourcekit:31 bash -c "cd /swift && ./xswift-test-spm"
      env: JOB=Linux310
      sudo: required
      services: docker


