language: generic

matrix:
  include:
    - script:
        - bin/fetch-configlet
        - bin/configlet lint .
        - docker run -v `pwd`:/swift swift:4.2 bash -c "cd /swift && ./xswift-test-spm"
      env: JOB=Linux42x
      sudo: required
      services: docker
